__1. Установить, какие произведения матриц  AB  и  BA  определены, и найти размерности полученных матриц:__

а)  A  — матрица  4×2 ,  B  — матрица  4×2 ; - не опредены

б)  A  — матрица  2×5 ,  B  — матрица  5×3 ; -  определено BA 2×3

в)  A  — матрица  8×3 ,  B  — матрица  3×8 ; - определены AB   и  BA 8×8

г)  A  — квадратная матрица  4×4 ,  B  — квадратная матрица  4×4 . определены AB  и  BA 4×4

__2. Найти сумму и произведение матриц__

$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

A + B =  $C=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$

In [3]:
import numpy as np
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица С = A + B\n{a + b}')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]


A * B =  $C=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$

In [5]:
a = np.array([[1, -2], [3, 0]])
b = np.array([[4, -1], [0, 5]])

print(f'Матрица A\n{a}')
print(f'Матрица B\n{b}')
print(f'Матрица AB\n{np.dot(a, b)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$, $2B=\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$, $4C=\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}.$


$3A-2B+4C$ =  $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$ 

In [7]:
a = np.array([[1, 7], [3, -6]])
k = 3

b = np.array([[0, 5], [2, -1]])
m = 2

c = np.array([[2, -4], [1, 1]])
n = 4

print(f'Матрица 3*А\n{k*a}')
print(f'Матрица 2*B\n{m*b}')
print(f'Матрица 4*C\n{n*c}')

print(f'Матрица 3A - 2B + 4C\n{k*a - m*b + n*c}')

Матрица 3*А
[[  3  21]
 [  9 -18]]
Матрица 2*B
[[ 0 10]
 [ 4 -2]]
Матрица 4*C
[[  8 -16]
 [  4   4]]
Матрица 3A - 2B + 4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица 

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.


$$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3\\ 
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}.$$


$$AA^{T}=\begin{pmatrix}
16+1 & 20-2 & 8+3\\ 
20-2 & 25+4 & 10-6\\ 
18+3 & 10-6 & 4+9\\
\end{pmatrix}.$$

$$AA^{T}=\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\\
\end{pmatrix}.$$

In [9]:
a = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица:\n{a}')
print(f'Транспонированная матрица:\n{a.T}')
print(f'Матрица A*AT\n{np.dot(a, a.T)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
Матрица A*AT
[[17 18 11]
 [18 29  4]
 [11  4 13]]



$$A=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}, \;A^{T}=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3\\ 
\end{pmatrix}.$$


$$A^{T}A=\begin{pmatrix}
16+25+4 & 4-10+6\\ 
4-10+6 & 1+4+9\\ 
\end{pmatrix}.$$

$$A^{T}A=\begin{pmatrix}
45 & 0\\ 
0 & 45\\ 
\end{pmatrix}.$$

In [11]:
print(f'Матрица A*AT\n{np.dot(a.T, a)}')

Матрица A*AT
[[45  0]
 [ 0 14]]


__Методичка 4__

__1. Вычислить определитель:__

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$


= $$sin^2x + cos^2x = 1$$


   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$

= $$ 4\cdot5\cdot9= 180$$

In [7]:
import math
a = np.array([[4, 4,3], [0, 5,1], [0,0,9]])

print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[4 4 3]
 [0 5 1]
 [0 0 9]]
Определитель:
180


   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


$$\begin{vmatrix}
+ & - & +\\ 
- & + & -\\ 
+ & - & +
\end{vmatrix}.$$ 

решала на листочке (приложу фото)
= 0

In [9]:
a = np.array([[1,2,3], [4, 5,6], [7,8,9]])

print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Определитель:
0


__2. Определитель матрицы $A$ равен $4$.__ Найти:

   а) $det(A^{2})$; = 16 так как $det(AB)=detA\cdot detB.$
    
   б) $det(A^{T})$; = 4 так как $detA^{T}=detA.$
    
   в) $det(2A)$. = 8



__3.  Доказать, что матрица__

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

In [10]:
a = np.array([[-2,7,-3], [4, -14,6], [-3,7,13]])

print(f'Матрица:\n{a}')
print(f'Определитель:\n{np.linalg.det(a):.0f}')

Матрица:
[[ -2   7  -3]
 [  4 -14   6]
 [ -3   7  13]]
Определитель:
0


Так как определитель равен 0, матрица является вырожденной

__4. Найти ранг матрицы:__

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

Третья строка является суммой первой и второй, ее можно отбросить

$\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
\end{pmatrix};$

Вычтем из второй строки первую 

$\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
\end{pmatrix};$

Ранг равен 2

In [12]:
x = [1, 2, 3]
y = [1, 1, 1]
z = [2, 3, 4]

a = np.array([x, y, z])
r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 2


   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

Третья строка является суммой первой и второй, ее можно отбросить
$\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}.$

Ранг равен 3

In [21]:
x = [0, 0, 2, 1]
y = [0, 0, 2, 2]
с = [0, 0, 4, 3]
с = [2, 3, 5, 6]

a = np.array([x, y, с])

r = np.linalg.matrix_rank(a)

print(f'Ранг матрицы: {r}')

Ранг матрицы: 3
